name: FAST API Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./pro/
    
    strategy:
      matrix:
        python-version: [ 3.9 ]
    
    env:
      MODE: "WEALTH"

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Test App Code
        run: python ./mainApp/test.py
